# -*- mode: ruby -*-
# vi: set ft=ruby :

disk = 'C:\Users\fmariano\Documents\tmp\vbox-disks\ha-master-secondDisk.vdi'

Vagrant.configure("2") do |config|
  config.vm.define "ha-master1" do |ha|
    ha.vm.box = "ha-master1"
    ha.vm.hostname = "ha-master1"
    ha.vm.box = "bento/centos-7"
    ha.vm.network "private_network", ip: "192.168.77.11"
    ha.vm.network "private_network", ip: "192.168.78.11"

    ssh_pub_key = File.readlines("files/id_rsa.pub").first.strip

    ha.vm.provider "virtualbox" do |vb|
      unless File.exist?(disk)
        vb.customize ['createhd', '--filename', disk, '--variant', 'Fixed', '--size', 6144]
        vb.customize ['modifyhd', disk, '--type', 'shareable']
      end
      vb.memory = "1024"
      vb.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk]
    end

    ha.vm.provision "shell", run: "always", inline: <<-SHELL
      useradd centos
      mkdir /home/centos/.ssh
      echo #{ssh_pub_key} >> /home/centos/.ssh/authorized_keys
      cp -a "/vagrant/files/id_rsa.pub" /home/centos/.ssh/id_rsa.pub
      chmod 400 /home/centos/.ssh/id_rsa.pub
      mkdir /root/.ssh
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      cp -a "/vagrant/files/id_rsa.pub" /root/.ssh/id_rsa.pub
      chmod 400 /root/.ssh/id_rsa.pub
      cp -a "/vagrant/files/sshd_config" /etc/ssh/sshd_config
      cp -a "/vagrant/files/sudoers" /etc/sudoers
      chown root.root /etc/sudoers
      chmod 660 /etc/sudoers
      usermod -a -G wheel centos
      systemctl restart sshd
      yum upgrade kernel -y
      yum install kernel-devel -y
    SHELL
  end

  config.vm.define "ha-master2" do |ha|
    ha.vm.box = "ha-master2"
    ha.vm.hostname = "ha-master2"
    ha.vm.box = "bento/centos-7"
    ha.vm.network "private_network", ip: "192.168.77.12"
    ha.vm.network "private_network", ip: "192.168.78.12"

    ssh_pub_key = File.readlines("files/id_rsa.pub").first.strip

    ha.vm.provider "virtualbox" do |vb|
      unless File.exist?(disk)
        vb.customize ['createhd', '--filename', disk, '--variant', 'Fixed', '--size', 100]
        vb.customize ['modifyhd', disk, '--type', 'shareable']
      end
      vb.memory = "1024"
      vb.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk]
    end

    ha.vm.provision "shell", run: "always", inline: <<-SHELL
      useradd centos
      mkdir /home/centos/.ssh
      echo #{ssh_pub_key} >> /home/centos/.ssh/authorized_keys
      cp -a "/vagrant/files/id_rsa.pub" /home/centos/.ssh/id_rsa.pub
      chmod 400 /home/centos/.ssh/id_rsa.pub
      mkdir /root/.ssh
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      cp -a "/vagrant/files/id_rsa.pub" /root/.ssh/id_rsa.pub
      chmod 400 /root/.ssh/id_rsa.pub
      cp -a "/vagrant/files/sshd_config" /etc/ssh/sshd_config
      cp -a "/vagrant/files/sudoers" /etc/sudoers
      chown root.root /etc/sudoers
      chmod 660 /etc/sudoers
      usermod -a -G wheel centos
      systemctl restart sshd
      yum upgrade kernel -y
      yum install kernel-devel -y
    SHELL
  end

  config.vm.define "ha-master3" do |ha|
    ha.vm.box = "ha-master3"
    ha.vm.hostname = "ha-master3"
    ha.vm.box = "bento/centos-7"
    ha.vm.network "private_network", ip: "192.168.77.13"
    ha.vm.network "private_network", ip: "192.168.78.13"

    ssh_pub_key = File.readlines("files/id_rsa.pub").first.strip

    ha.vm.provider "virtualbox" do |vb|
      unless File.exist?(disk)
        vb.customize ['createhd', '--filename', disk, '--variant', 'Fixed', '--size', 100]
        vb.customize ['modifyhd', disk, '--type', 'shareable']
      end
      vb.memory = "1024"
      vb.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk]
    end

    ha.vm.provision "shell", run: "always", inline: <<-SHELL
      useradd centos
      mkdir /home/centos/.ssh
      echo #{ssh_pub_key} >> /home/centos/.ssh/authorized_keys
      cp -a "/vagrant/files/id_rsa.pub" /home/centos/.ssh/id_rsa.pub
      chmod 400 /home/centos/.ssh/id_rsa.pub
      mkdir /root/.ssh
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      cp -a "/vagrant/files/id_rsa.pub" /root/.ssh/id_rsa.pub
      chmod 400 /root/.ssh/id_rsa.pub
      cp -a "/vagrant/files/sshd_config" /etc/ssh/sshd_config
      cp -a "/vagrant/files/sudoers" /etc/sudoers
      chown root.root /etc/sudoers
      chmod 660 /etc/sudoers
      usermod -a -G wheel centos
      systemctl restart sshd
      yum upgrade kernel -y
      yum install kernel-devel -y
    SHELL
  end

  config.vm.define "ha-node1" do |ha|
    ha.vm.box = "ha-node1"
    ha.vm.hostname = "ha-node1"
    ha.vm.box = "bento/centos-7"
    ha.vm.network "private_network", ip: "192.168.77.21"
    ha.vm.memory = "512"

    ssh_pub_key = File.readlines("files/id_rsa.pub").first.strip

    ha.vm.provision "shell", run: "always", inline: <<-SHELL
      useradd centos
      mkdir /home/centos/.ssh
      echo #{ssh_pub_key} >> /home/centos/.ssh/authorized_keys
      cp -a "/vagrant/files/id_rsa.pub" /home/centos/.ssh/id_rsa.pub
      chmod 400 /home/centos/.ssh/id_rsa.pub
      mkdir /root/.ssh
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      cp -a "/vagrant/files/id_rsa.pub" /root/.ssh/id_rsa.pub
      chmod 400 /root/.ssh/id_rsa.pub
      cp -a "/vagrant/files/sshd_config" /etc/ssh/sshd_config
      cp -a "/vagrant/files/sudoers" /etc/sudoers
      chown root.root /etc/sudoers
      chmod 660 /etc/sudoers
      usermod -a -G wheel centos
      systemctl restart sshd
      yum upgrade kernel -y
      yum install kernel-devel -y
    SHELL

  end
  config.vm.define "ha-node2" do |ha|
    ha.vm.box = "ha-node2"
    ha.vm.hostname = "ha-node2"
    ha.vm.box = "bento/centos-7"
    ha.vm.network "private_network", ip: "192.168.77.22"
    ha.vm.memory = "512"

    ssh_pub_key = File.readlines("files/id_rsa.pub").first.strip
    ha.vm.provision "shell", run: "always", inline: <<-SHELL
      useradd centos
      mkdir /home/centos/.ssh
      echo #{ssh_pub_key} >> /home/centos/.ssh/authorized_keys
      cp -a "/vagrant/files/id_rsa.pub" /home/centos/.ssh/id_rsa.pub
      chmod 400 /home/centos/.ssh/id_rsa.pub
      mkdir /root/.ssh
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      cp -a "/vagrant/files/id_rsa.pub" /root/.ssh/id_rsa.pub
      chmod 400 /root/.ssh/id_rsa.pub
      cp -a "/vagrant/files/sshd_config" /etc/ssh/sshd_config
      cp -a "/vagrant/files/sudoers" /etc/sudoers
      chown root.root /etc/sudoers
      chmod 660 /etc/sudoers
      usermod -a -G wheel centos
      systemctl restart sshd
      yum upgrade kernel -y
      yum install kernel-devel -y
    SHELL

  end

end
